### ISSUE TITLE
max idle time doesn't apply for last build running

### ISSUE THREAD

**Issue by ghazninattarshah** [windsource/picus#18]
when max idle time is set to low like 5 mins, and the job count is 0, it means the last build is still running, the agent shutdown abruptly even when the build is not finished.

**Comment by windsource** [comment]
@ghazninattarshah Picus starts the idle timer when running_count is 0 again. During the build running_count is > 0. I have just checked this with Woodpecker 2.7.1 and it works fine even with long build times and short `PICUS_MAX_IDLE_TIME`.

**Comment by ghazninattarshah** [comment]
<img width="1161" alt="image" src="https://github.com/user-attachments/assets/9443a29a-dbd7-45f5-ab5b-a81a4360ae99">

<img width="1235" alt="image" src="https://github.com/user-attachments/assets/140c7368-af3d-438c-aed8-02327aaf5211">

<img width="831" alt="image" src="https://github.com/user-attachments/assets/25d626ad-b0b4-422f-be27-78bea07b83b8">

**Comment by ghazninattarshah** [comment]
@windsource I had an agent name for `PICUS_WOODPECKER_AGENT_ID` which was wrong, now corrected.
and then `PICUS_AGENT_WOODPECKER_BACKEND` is not set. updated and below is the config. 

```
# docker-compose.yml
version: '3'
networks:
  woodpecker:
    external: false
services:
  picus-1:
    image: ghcr.io/windsource/picus:latest
    environment:
      - PICUS_MAX_IDLE_TIME=20m
      - PICUS_PROVIDER_TYPE=aws
      - PICUS_WOODPECKER_SERVER=${WOODPECKER_SERVER}
      - PICUS_WOODPECKER_TOKEN=${WOODPECKER_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - PICUS_AGENT_WOODPECKER_FILTER_LABELS=platform=linux/amd64,backend=docker,repo=*
      - PICUS_AGENT_WOODPECKER_BACKEND=docker
      - PICUS_AWS_INSTANCE_ID=i-0fa082e631a9a4785
      - PICUS_WOODPECKER_AGENT_ID=10
    restart: always
  picus-2:
    image: ghcr.io/windsource/picus:latest
    # command: agent
    environment:
      - PICUS_MAX_IDLE_TIME=20m
      - PICUS_PROVIDER_TYPE=aws
      - PICUS_WOODPECKER_SERVER=${WOODPECKER_SERVER}
      - PICUS_WOODPECKER_TOKEN=${WOODPECKER_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - PICUS_AGENT_WOODPECKER_FILTER_LABELS=platform=linux/amd64,backend=docker,repo=*
      - PICUS_AGENT_WOODPECKER_BACKEND=docker
      - PICUS_AWS_INSTANCE_ID=i-0bd3b5effabecced3
      - PICUS_WOODPECKER_AGENT_ID=11
    restart: always
```

@windsource, after adding those two environment variables, it seems to be working fine. 
thank you for your help.

I have been looking for auto start ci VM for woodpecker and found Picus instantly. this really help to reduce cloud cost for ci.
