### ISSUE TITLE
aws: smithy connection was poisoned

### ISSUE THREAD

**Issue by ghazninattarshah** [windsource/picus#19]
agent-picus-2-1  | [2024-10-21T08:49:08Z INFO  picus::strategy] Agent is not running. 5 pending job(s) for that agent
agent-picus-2-1  | [2024-10-21T08:49:08Z INFO  picus::strategy] 5 pending jobs. Starting agent.
agent-picus-2-1  | [2024-10-21T08:49:08Z INFO  picus::aws] Starting instance ...
agent-picus-2-1  | [2024-10-21T08:49:08Z INFO  aws_smithy_runtime_api::client::connection] smithy connection was poisoned
agent-picus-2-1  | [2024-10-21T08:49:09Z INFO  aws_smithy_runtime_api::client::connection] smithy connection was poisoned
agent-picus-2-1  | [2024-10-21T08:49:11Z INFO  aws_smithy_runtime_api::client::connection] smithy connection was poisoned
agent-picus-2-1  | [2024-10-21T08:49:11Z ERROR picus::strategy] AgentProvider could not start server: service error

**Comment by windsource** [comment]
This seems to be similar to https://github.com/awslabs/aws-sdk-rust/issues/1154. I have updated all packages and now `aws-smithy-runtime` is on version 1.7.2. @ghazninattarshah Could please try with `ghcr.io/windsource/picus:latest` and check if that works? You probably need to pull the image before in order to get the fixed version.

**Comment by ghazninattarshah** [comment]
I do not see the issue anymore. That fixes it. thanks, @windsource 

is there a way to set the logger level to error? or just log when starting and stopping instance, I do not want log when the picus poll the woodpecker API like every 10s.

**Comment by windsource** [comment]
@ghazninattarshah when you set an environment variable `RUST_LOG=warn` you should see only warning and error messages. You can also do that just for picus with `RUST_LOG="picus=warn"`.

**Comment by ghazninattarshah** [comment]
I don't see the connectivity issue anymore, hence this issue shall be closed.

**Comment by windsource** [comment]
To log just starting and stopping instances but not the API calls and the remaining idle time

```
RUST_LOG="info,picus::strategy=warn"
```

should work.
